Hephaestus/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.contrib.auth import views as v
from domain.views.employee_views.employres_views import *
from domain.views.employee_views.general_views import *
from domain.views.employers_views.general_views import *
from domain.views.general_views.general_views import *
from domain.views.employee_views.job_seeker_views import *
from domain.views.job_seeker_views.general_views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_view, name='home'),
    path('eme/', include([
        path('applications/', include([
            path('', applications_view, name='applications_view'),
            path('<str:ordering>', applications_view, name='applications_view'),
            path('detail/<str:application_id>', application_detail_view, name='applications_view_detail'),
        ])),

        path('interview/', include([
            path('invite/<str:application_response_id>', invite_job_seeker_on_interview,
                 name='invite_job_seeker_on_interview'),
            path('feedback/<str:interview_id>', create_interview_feedback, name='create_interview_feedback'),
            path('', employee_interviews_view, name='employee_interviews_view'),
            path('<int:archive>', employee_interviews_view, name='employee_interviews_view'),
        ])),

        path('jobseeker/', include([
            path('view', job_seeker_all_view, name='job_seeker_list'),
            path('<str:job_seeker_id>', job_seeker_view, name='job_seeker_view'),
        ])),

        path('responce/reject/<str:application_response_id>', reject_job_seeker_response,
             name='reject_job_seeker_response'),

        path('references/', include([
            path('', references_view, name='references'),
            path('<str:reference>', references_view, name='references'),
        ])),

        path('reports/', include([
            path('', select_report_view, name='select_report_view'),
            path('applications_report', applications_report, name='applications_report'),
            path('users_report', users_report, name='users_report'),
        ])),
    ])),

    path('js/', include([
        path('profile/', include([
            path('skills', skills_view, name='job_seeker_skills'),
            path('specializations', specialization_view, name='job_seeker_specializations'),
            path('software_and_hardware_tools', software_and_hardware_tools_view,
                 name='job_seeker_software_and_hardware_tools'),
            path('education/', include([
                path('add', job_seeker_education_view, name='job_seeker_education'),
                path('delete/<int:education_id>', delete_education_view, name='delete_education'),
            ])),
            path('work_experience/', include([
                path('add', job_seeker_work_experience_view, name='job_seeker_work_experience'),
                path('delete/<int:work_experience_id>', delete_work_experience_view, name='delete_work_experience_view'),
            ])),
        ])),
        path('application/', include([
            path('view/<str:application_id>', job_seeker_application_view, name='job_seeker_application_view'),
            path('response/', include([
                path('all/', include([
                    path('', job_seeker_application_responses_all_view,
                         name='job_seeker_application_responses_all_view'),
                    path('archive', job_seeker_application_responses_all_archive_view,
                         name='job_seeker_application_responses_all_archive_view'),
                ])),
                path('<str:application_id>/', job_seeker_application_response_create,
                     name='job_seeker_application_response_create'),
                path('<str:application_id>/withdraw', job_seeker_application_response_withdraw,
                     name='job_seeker_application_response_withdraw'),
            ])),
            path('interview/', include([
                path('all/', include([
                    path('', job_seeker_interviews_view, name='job_seeker_interviews_view'),
                    path('<int:archive>', job_seeker_interviews_view, name='job_seeker_interviews_view'),
                ])),
                path('accept/<str:interview_id>', accept_invite_on_interview, name='accept_invite_on_interview'),
                path('reject/<str:interview_id>', reject_invite_on_interview, name='reject_invite_on_interview'),
            ])),
        ]))
    ])),

    path('emr/', include([
        path('profile/', include([
            path('edit/', include([
                path('organization/', include([
                    path('create/', organization_create_view, name='organization_create'),
                    path('apply/<str:organization_id>', organization_apply_view, name='organization_apply'),
                    path('edit/<str:organization_id>', organization_edit_view, name='organization_edit'),
                    path('untie/', organization_untie_view, name='organization_untie'),
                ]))
            ]))
        ])),
        path('applications/', include([
            path('create', application_create_view, name='application_create'),
            path('apply/<str:application_response_id>', apply_job_seeker, name='apply_job_seeker'),
        ])),
        path('job_seeker/<str:job_seeker_id>', allowed_job_seeker_view, name='allowed_job_seeker_view'),
    ])),

    path('login', v.LoginView.as_view(next_page='home'), name='login'),
    path('logout', v.LogoutView.as_view(next_page='login'), name='logout'),

    path('select_user_type', choose_user_type, name='select_user_type'),
    path('registration/<str:user_type>', registration, name='registration'),

    path('profile/', profile, name='user_profile'),
    path('profile/edit', profile_update, name='profile_update'),

    path('organization/<str:organization_id>', organization_view, name='organization_view'),

    path('error_page/<str:error_message>', error_view, name='error_page'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

domain/models.py
import datetime
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.contrib.auth.models import AbstractUser


class CustomUser(AbstractUser):
    patronymic = models.CharField(max_length=255, blank=False, null=False, verbose_name='Отчество')
    phone_number = models.CharField(max_length=18, blank=False, null=False, verbose_name='Номер телефона')
    profile_photo = models.ImageField(blank=True, null=True, verbose_name='Фото профиля', upload_to='user_photos')

    def __str__(self):
        return '%s %s %s' % (self.last_name, self.first_name, self.patronymic)

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'


class OrganizationalLegalForm(models.Model):
    name = models.CharField(max_length=90, blank=False, null=False, verbose_name='Наименование')
    short_name = models.CharField(max_length=10, blank=False, null=False, verbose_name='Краткое наименование')

    def __str__(self):
        return '%s' % self.short_name

    class Meta:
        verbose_name = 'Организационно-правовая форма'
        verbose_name_plural = 'Организационно-правовые формы'


class Address(models.Model):
    locality = models.CharField(max_length=255, blank=False, null=False, verbose_name='Населенный пункт')
    street = models.CharField(max_length=255, blank=True, null=True, verbose_name='Улица')
    number_of_building = models.CharField(max_length=31, blank=True, null=True, verbose_name='Номер строения')
    apartment_number = models.CharField(max_length=31, blank=True, null=True, verbose_name='Номер квартиры/офиса')
    latitude = models.FloatField(blank=True, null=True, verbose_name='Широта')
    longitude = models.FloatField(blank=True, null=True, verbose_name='Долгота')
    map_link = models.URLField(max_length=2083, blank=True, null=True, verbose_name='Ссылка на карты')

    def __str__(self):
        return '%s' % self.map_link

    class Meta:
        verbose_name = 'Адрес'
        verbose_name_plural = 'Адреса'


class Organization(models.Model):
    name = models.CharField(max_length=255, blank=False, null=False, verbose_name='Наименование')
    payment_account = models.CharField(max_length=20, blank=False, null=False, verbose_name='Расчетный счет')
    okved_kode = models.CharField(max_length=9, blank=True, null=True, verbose_name='Код ОКВЭД')
    organizational_legal_form = models.ForeignKey('OrganizationalLegalForm', on_delete=models.PROTECT,
                                                  null=False, blank=False, verbose_name='ОПФ')
    inn = models.CharField(max_length=12, blank=False, null=False, verbose_name='ИНН')
    address = models.ForeignKey('Address', on_delete=models.PROTECT,
                                null=False, blank=False, verbose_name='Адрес')
    about = models.TextField(blank=True, null=True, verbose_name='Описание организации')
    organization_logo = models.ImageField(blank=True, null=True, verbose_name='Логотип организации',
                                          upload_to='organization_logos')

    def __str__(self):
        return '%s "%s"' % (self.organizational_legal_form.short_name, self.name)

    class Meta:
        verbose_name = 'Организация'
        verbose_name_plural = 'Организации'


class Employer(CustomUser):
    organization = models.ForeignKey('Organization', on_delete=models.CASCADE,
                                     blank=True, null=True, verbose_name='Организация')
    position = models.CharField(max_length=90, blank=True, null=True, verbose_name='Должность')

    def __str__(self):
        return '%s %s %s' % (self.last_name, self.first_name, self.patronymic)

    class Meta:
        verbose_name = 'Работодатель'
        verbose_name_plural = 'Работодатели'


class EmployeePosition(models.Model):
    name = models.CharField(max_length=90, blank=False, null=False, verbose_name='Наименование')

    def __str__(self):
        return '%s' % self.name

    class Meta:
        verbose_name = 'Должность'
        verbose_name_plural = 'Должности'


class Employee(CustomUser):
    date_of_employment = models.DateField(blank=True, null=True, verbose_name='Дата приёма', auto_now=True)
    date_of_dismissal = models.DateField(blank=True, null=True, verbose_name='Дата увольнения')
    employee_position = models.ForeignKey('EmployeePosition', on_delete=models.PROTECT,
                                          null=False, blank=False, verbose_name='Должность')

    def __str__(self):
        return '%s %s %s, %s' % (self.last_name, self.first_name, self.patronymic, self.employee_position.name)

    class Meta:
        verbose_name = 'Работник'
        verbose_name_plural = 'Работники'


class EducationalOrganization(models.Model):
    name = models.CharField(max_length=255, blank=False, null=False, verbose_name='Наименование')
    address = models.ForeignKey('Address', on_delete=models.PROTECT,
                                null=False, blank=False, verbose_name='Адрес')

    def __str__(self):
        return '%s' % self.name

    class Meta:
        verbose_name = 'Образовательное учреждение'
        verbose_name_plural = 'Образовательные учреждения'


class EducationLevel(models.Model):
    name = models.CharField(max_length=90, blank=False, null=False, verbose_name='Наименование')
    code = models.IntegerField(validators=[
        MinValueValidator(0), MaxValueValidator(10)], blank=False, null=False,
        verbose_name='Код уровня профессионального образования')

    def __str__(self):
        return '%s' % self.name

    class Meta:
        verbose_name = 'Уровень образования'
        verbose_name_plural = 'Уровни образования'


class Education(models.Model):
    organization = models.ForeignKey('EducationalOrganization', on_delete=models.PROTECT,
                                     null=False, blank=False, verbose_name='Образовательное учреждение')
    name = models.CharField(max_length=255, blank=False, null=False, verbose_name='Наименование')
    code = models.CharField(max_length=9, blank=True, null=True, verbose_name='Код специальности')
    education_level = models.ForeignKey('EducationLevel', on_delete=models.PROTECT, null=False, blank=False,
                                        verbose_name='Уровень образования')

    def __str__(self):
        return '%s %s %s' % (self.name, self.code, self.organization)

    class Meta:
        verbose_name = 'Образование'
        verbose_name_plural = 'Образования'


class Skill(models.Model):
    name = models.CharField(max_length=100, blank=False, null=False, verbose_name='Наименование')

    def __str__(self):
        return '%s' % self.name

    class Meta:
        verbose_name = 'Навык'
        verbose_name_plural = 'Навыки'


class Specialization(models.Model):
    name = models.CharField(max_length=255, blank=False, null=False, verbose_name='Наименование')

    def __str__(self):
        return '%s' % self.name

    class Meta:
        verbose_name = 'Специализация'
        verbose_name_plural = 'Специализации'


class SoftwareAndHardwareTool(models.Model):
    name = models.CharField(max_length=255, blank=False, null=False, verbose_name='Наименование')

    def __str__(self):
        return '%s' % self.name

    class Meta:
        verbose_name = 'Ключевой навык'
        verbose_name_plural = 'Ключевые навыки'


class WorkSchedule(models.Model):
    name = models.CharField(max_length=255, blank=False, null=False, verbose_name='Наименование')

    def __str__(self):
        return '%s' % self.name

    class Meta:
        verbose_name = 'График работы'
        verbose_name_plural = 'Графики работы'


class WorkFormat(models.Model):
    name = models.CharField(max_length=255, blank=False, null=False, verbose_name='Наименование')

    def __str__(self):
        return '%s' % self.name

    class Meta:
        verbose_name = 'Формат работы'
        verbose_name_plural = 'Форматы работы'


class JobSeeker(CustomUser):
    LOCATION_CHOICES = [
        ('remote', 'Удалённая работа'),
        ('local', 'Работа в городе проживания'),
        ('relocation', 'Готовность к переезду')
    ]

    birthdate = models.DateField(blank=True, null=True, verbose_name='Дата рождения')
    address = models.ForeignKey('Address', blank=True, null=True, on_delete=models.PROTECT, verbose_name='Адрес')
    skill = models.ManyToManyField('Skill', blank=True, verbose_name='Навыки')
    specialization = models.ManyToManyField('Specialization', blank=True, verbose_name='Специализация')
    about = models.TextField(blank=True, null=True, verbose_name='О себе')
    work_location_preference = models.CharField(max_length=15, choices=LOCATION_CHOICES, default='local',
                                                verbose_name='Место желаемой работы')

    def __str__(self):
        return '%s %s %s' % (self.last_name, self.first_name, self.patronymic)

    class Meta:
        verbose_name = 'Соискатель'
        verbose_name_plural = 'Соискатели'


class WorkExperience(models.Model):
    job_seeker = models.ForeignKey('JobSeeker', blank=False, null=False,
                                   on_delete=models.CASCADE, verbose_name='Соискатель')
    date_of_employment = models.DateField(blank=False, null=False, verbose_name='Дата приёма')
    date_of_dismissal = models.DateField(blank=True, null=True, verbose_name='Дата увольнения')
    organization = models.CharField(max_length=255, blank=False, null=False, verbose_name='Организация')
    position = models.ForeignKey('Position', blank=False, null=False,
                                 on_delete=models.PROTECT, verbose_name='Должность')

    def __str__(self):
        return '%s %s лет %s' % \
            (self.job_seeker.__str__(),
             ((self.date_of_dismissal - self.date_of_employment
               if self.date_of_dismissal else datetime.date.today() - self.date_of_employment).days) // 365,
             self.position)

    class Meta:
        verbose_name = 'Опыт работы'

domain/templates/employers_templates/organization/components/organization_form.html
{% block content %}
    <form method="POST" class="input-form flex-vertical gap-2em" enctype="multipart/form-data">
        {% csrf_token %}
        <h1 class="title text-size-larger">Основная информация</h1>
        <p>
            <label for="{{ form.name.id_for_label }}">{{ form.name.label }}:</label>
            {{ form.name }}
        </p>
        <p>
            <label for="{{ form.organizational_legal_form.id_for_label }}">{{ form.organizational_legal_form.label }}:</label>
            {{ form.organizational_legal_form }}
        </p>
        <p>
            <label for="{{ form.about.id_for_label }}">{{ form.about.label }}:</label>
            {{ form.about|add_class:'input-field' }}
        </p>
        <p style="text-wrap: nowrap">
            <label for="{{ form.organization_logo.id_for_label }}">{{ form.organization_logo.label }}:</label>
            <input type="file" name="organization_logo" accept="image/*" id="id_organization_logo">
        </p>
        <p style="display: none">
            <label for="{{ form.okved_kode.id_for_label }}">{{ form.okved_kode.label }}:</label>
            {{ form.okved_kode }}
        </p>
        <div class="flex-horizontal gap-2em" style="align-items: baseline; "><label
                for="{{ form.okved_kode.id_for_label }}">Введите код или род деятельности
            организации:</label>
            <div class="flex-vertical gap-1em" style="flex: 1">
                <textarea id="okved2" name="okved2" class="input-field" style="width: 100%" rows="1">{% if form.okved_kode.value %}{{ form.okved_kode.value }}{% endif %}</textarea>
            </div>
        </div>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
        <link href="http://cdn.jsdelivr.net/npm/suggestions-jquery@22.6.0/dist/css/suggestions.min.css"
              rel="stylesheet"/>
        <script src="http://cdn.jsdelivr.net/npm/suggestions-jquery@22.6.0/dist/js/jquery.suggestions.min.js"></script>
        <script>
            $("#okved2").suggestions({
                token: "{{ DADATA_API_KEY }}",
                type: "OKVED2",
                /* Вызывается, когда пользователь выбирает одну из подсказок */
                onSelect: function (suggestion) {
                    // Помещаем значение кода ОКВЭД в скрытое поле
                    $("#{{ form.okved_kode.id_for_label }}").val(suggestion.data.kod);
                }
            });
        </script>
        <h1 class="title text-size-larger">Финансовая информация</h1>
        <p>
            <label for="{{ form.payment_account.id_for_label }}">{{ form.payment_account.label }}:</label>
            {{ form.payment_account }}
        </p>
        <p>
            <label for="{{ form.inn.id_for_label }}">{{ form.inn.label }}:</label>
            {{ form.inn }}
        </p>
        <h1 class="title text-size-larger">Адрес</h1>
        <p class="flex-horizontal" style="display: none">
            <label for="{{ form.locality.id_for_label }}">{{ form.locality.label }}:</label>
            {{ form.locality }}
            <label for="{{ form.street.id_for_label }}">{{ form.street.label }}:</label>
            {{ form.street|add_class:"width-180" }}
            <label for="{{ form.number_of_building.id_for_label }}">Дом:</label>
            {{ form.number_of_building }}
            <label for="{{ form.apartment_number.id_for_label }}">Помещение:</label>
            {{ form.apartment_number }}
        </p>
        <div class="flex-horizontal gap-2em" style="align-items: baseline; "><label>Введите адрес
            организации:</label>
            <div class="flex-vertical gap-1em" style="flex: 1">
                <input id="address" name="address" type="text" class="input-field" style="width: 100%"
                       value="{% if form.locality.value %}{{ form.locality.value }} {{ form.street.value }} {{ form.number_of_building.value }} {{ form.apartment_number.value }}{% endif %}"/>
            </div>
        </div>

        <script>
            $("#address").suggestions({
                token: "{{ DADATA_API_KEY }}",
                type: "ADDRESS",
                /* Вызывается, когда пользователь выбирает одну из подсказок */
                onSelect: function (suggestion) {
                    // Заполнение скрытых полей адреса значениями из подсказки
                    $("#id_locality").val(suggestion.data.city);
                    $("#id_street").val(suggestion.data.street);
                    $("#id_number_of_building").val(suggestion.data.house);
                    $("#id_apartment_number").val(suggestion.data.flat);
                }
            });
        </script>
        {% if form.errors %}
            <p class="error-message">{{ form.errors }}</p>
        {% endif %}
        <button type="submit" class="button submit" style="width: fit-content;">Сохранить</button>
    </form>
{% endblock content %}