Hephaestus/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.contrib.auth import views as v
from domain.views.employee_views.employres_views import *
from domain.views.employee_views.general_views import *
from domain.views.employers_views.general_views import *
from domain.views.general_views.general_views import *
from domain.views.employee_views.job_seeker_views import *
from domain.views.job_seeker_views.general_views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_view, name='home'),
    path('eme/', include([
        path('applications/', include([
            path('', applications_view, name='applications_view'),
            path('<str:ordering>', applications_view, name='applications_view'),
            path('detail/<str:application_id>', application_detail_view, name='applications_view_detail'),
        ])),

        path('interview/', include([
            path('invite/<str:application_response_id>', invite_job_seeker_on_interview,
                 name='invite_job_seeker_on_interview'),
            path('feedback/<str:interview_id>', create_interview_feedback, name='create_interview_feedback'),
            path('', employee_interviews_view, name='employee_interviews_view'),
            path('<int:archive>', employee_interviews_view, name='employee_interviews_view'),
        ])),

        path('jobseeker/', include([
            path('view', job_seeker_all_view, name='job_seeker_list'),
            path('<str:job_seeker_id>', job_seeker_view, name='job_seeker_view'),
        ])),

        path('responce/reject/<str:application_response_id>', reject_job_seeker_response,
             name='reject_job_seeker_response'),

        path('references/', include([
            path('', references_view, name='references'),
            path('<str:reference>', references_view, name='references'),
        ])),

        path('reports/', include([
            path('', select_report_view, name='select_report_view'),
            path('applications_report', applications_report, name='applications_report'),
            path('users_report', users_report, name='users_report'),
        ])),
    ])),

    path('js/', include([
        path('profile/', include([
            path('skills', skills_view, name='job_seeker_skills'),
            path('specializations', specialization_view, name='job_seeker_specializations'),
            path('software_and_hardware_tools', software_and_hardware_tools_view,
                 name='job_seeker_software_and_hardware_tools'),
            path('education/', include([
                path('add', job_seeker_education_view, name='job_seeker_education'),
                path('delete/<int:education_id>', delete_education_view, name='delete_education'),
            ])),
            path('work_experience/', include([
                path('add', job_seeker_work_experience_view, name='job_seeker_work_experience'),
                path('delete/<int:work_experience_id>', delete_work_experience_view, name='delete_work_experience_view'),
            ])),
        ])),
        path('application/', include([
            path('view/<str:application_id>', job_seeker_application_view, name='job_seeker_application_view'),
            path('response/', include([
                path('all/', include([
                    path('', job_seeker_application_responses_all_view,
                         name='job_seeker_application_responses_all_view'),
                    path('archive', job_seeker_application_responses_all_archive_view,
                         name='job_seeker_application_responses_all_archive_view'),
                ])),
                path('<str:application_id>/', job_seeker_application_response_create,
                     name='job_seeker_application_response_create'),
                path('<str:application_id>/withdraw', job_seeker_application_response_withdraw,
                     name='job_seeker_application_response_withdraw'),
            ])),
            path('interview/', include([
                path('all/', include([
                    path('', job_seeker_interviews_view, name='job_seeker_interviews_view'),
                    path('<int:archive>', job_seeker_interviews_view, name='job_seeker_interviews_view'),
                ])),
                path('accept/<str:interview_id>', accept_invite_on_interview, name='accept_invite_on_interview'),
                path('reject/<str:interview_id>', reject_invite_on_interview, name='reject_invite_on_interview'),
            ])),
        ]))
    ])),

    path('emr/', include([
        path('profile/', include([
            path('edit/', include([
                path('organization/', include([
                    path('create/', organization_create_view, name='organization_create'),
                    path('apply/<str:organization_id>', organization_apply_view, name='organization_apply'),
                    path('edit/<str:organization_id>', organization_edit_view, name='organization_edit'),
                    path('untie/', organization_untie_view, name='organization_untie'),
                ]))
            ]))
        ])),
        path('applications/', include([
            path('create', application_create_view, name='application_create'),
            path('apply/<str:application_response_id>', apply_job_seeker, name='apply_job_seeker'),
        ])),
        path('job_seeker/<str:job_seeker_id>', allowed_job_seeker_view, name='allowed_job_seeker_view'),
    ])),

    path('login', v.LoginView.as_view(next_page='home'), name='login'),
    path('logout', v.LogoutView.as_view(next_page='login'), name='logout'),

    path('select_user_type', choose_user_type, name='select_user_type'),
    path('registration/<str:user_type>', registration, name='registration'),

    path('profile/', profile, name='user_profile'),
    path('profile/edit', profile_update, name='profile_update'),

    path('organization/<str:organization_id>', organization_view, name='organization_view'),

    path('error_page/<str:error_message>', error_view, name='error_page'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

domain/forms.py
from datetime import timedelta
from datetime import datetime as dt
from django import forms
from domain.models import *


class EmployerForm(forms.ModelForm):
    surname = forms.CharField(max_length=90, label='Фамилия', error_messages={"required": "Введите фамилию"})
    name = forms.CharField(max_length=90, label='Имя', error_messages={"required": "Введите имя"})
    patronymic = forms.CharField(max_length=90, label='Отчество', error_messages={"required": "Введите отчество"})
    email = forms.EmailField(label='Почта', error_messages={"required": "Введите почту"})
    phone = forms.CharField(max_length=18, label='Номер телефона',
                            error_messages={"required": "Введите номер телефона"})
    profile_photo = forms.ImageField(label='Фото профиля', required=False)

    class Meta:
        model = Employer
        fields = ('surname', 'name', 'patronymic', 'phone', 'email', 'profile_photo')


class OrganizationForm(forms.ModelForm):
    position = forms.CharField(max_length=90, label='Должность',
                               error_messages={"required": "Введите должность"})
    locality = forms.CharField(max_length=255, label='Населенный пункт',
                               error_messages={"required": "Введите населённый пункт"})
    street = forms.CharField(max_length=255, label='Улица',
                             error_messages={"required": "Введите улицу"})
    number_of_building = forms.CharField(max_length=31, label='Номер строения',
                                         error_messages={"required": "Введите номер строения"})
    apartment_number = forms.CharField(max_length=31, label='Номер помещения',
                                       required=False)

    class Meta:
        model = Organization
        exclude = ['address']
        fields = '__all__'

    field_group_address = [locality, street, number_of_building, apartment_number]
    field_group_position = ['position']


class PositionForm(forms.Form):
    position = forms.CharField(max_length=90, label='Должность')


class ApplicationForm(forms.ModelForm):
    min_desired_date = (dt.now() + timedelta(days=10)).strftime('%Y-%m-%d')
    min_final_date = (dt.now() + timedelta(days=14)).strftime('%Y-%m-%d')
    position = forms.CharField(max_length=255, label='Должность')
    specialization = forms.ModelChoiceField(queryset=Specialization.objects.all(), label='Специализация')
    education_level = forms.ModelChoiceField(queryset=EducationLevel.objects.all(), required=False,
                                             label='Уровень образования')
    salary = forms.CharField(max_length=255, label='Зарплата')
    desired_date = forms.DateField(label='Желательный срок исполнения', widget=forms.DateInput(attrs={'type': 'date', 'min': min_desired_date}),)
    final_date = forms.DateField(label='Последний срок исполнения', widget=forms.DateInput(attrs={'type': 'date', 'min': min_final_date}),)
    skills = forms.ModelMultipleChoiceField(queryset=Skill.objects.all(), widget=forms.CheckboxSelectMultiple,
                                            required=False, label='Навыки')
    software_and_hardware_tools = forms.ModelMultipleChoiceField(queryset=SoftwareAndHardwareTool.objects.all(),
                                                                 required=False,
                                                                 widget=forms.CheckboxSelectMultiple,
                                                                 label='Требуемые программно-технические средства')
    experience = forms.IntegerField(label='Опыт(лет)')
    work_schedule = forms.ModelChoiceField(queryset=WorkSchedule.objects.all(), label='График работы')

    class Meta:
        model = Application
        fields = ['position', 'salary', 'desired_date', 'final_date', 'specialization', 'education_level', 'skills', 'software_and_hardware_tools',
                  'experience', 'work_schedule']

domain/forms/job_seekers_forms.py
from datetime import timedelta
from datetime import datetime as dt
from django import forms
from django.core.exceptions import ValidationError
from domain.models import *


class JobSeekerForm(forms.ModelForm):
    locality = forms.CharField(max_length=255, label='Населенный пункт', required=False)
    phone_number = forms.CharField(widget=forms.TextInput(attrs={'type': 'tel'}), label='Номер телефона')

    class Meta:
        model = JobSeeker
        fields = ['last_name', 'first_name', 'patronymic', 'phone_number', 'email', 'birthdate', 'locality', 'about',
                  'work_location_preference']
        widgets = {
            'birthdate': forms.DateInput(attrs={'type': 'date'}),
        }


class SkillsForm(forms.ModelForm):
    skills = forms.ModelMultipleChoiceField(queryset=Skill.objects.all().order_by('name'),
                                            widget=forms.CheckboxSelectMultiple,
                                            label='Навыки')
    new_skills = forms.CharField(label='Добавить новые навыки', required=False)

    class Meta:
        model = JobSeeker
        fields = ('skills', 'new_skills')


class SpecializationForm(forms.ModelForm):
    specializations = forms.ModelMultipleChoiceField(queryset=Specialization.objects.all().order_by('name'),
                                                     widget=forms.CheckboxSelectMultiple,
                                                     label='Специализации')
    new_specializations = forms.CharField(label='Добавить новые навыки', required=False)

    class Meta:
        model = JobSeeker
        fields = ('specializations', 'new_specializations')


class SoftwareAndHardwareToolForm(forms.ModelForm):
    software_and_hardware_tools = forms.ModelMultipleChoiceField(
        queryset=SoftwareAndHardwareTool.objects.all().order_by('name'),
        widget=forms.CheckboxSelectMultiple,
        label='Программно-технические средства')
    new_software_and_hardware_tools = forms.CharField(label='Добавить новые навыки', required=False)

    class Meta:
        model = SoftwareAndHardwareToolOfJobSeeker
        fields = ('software_and_hardware_tools', 'new_software_and_hardware_tools')


class EducationForm(forms.ModelForm):
    existing_education_organization = forms.ModelChoiceField(
        queryset=EducationalOrganization.objects.all(),
        required=False,
        label='Образовательная организация',
        empty_label='Выберите образовательную организацию'
    )
    education_organization_name = forms.CharField(
        max_length=255,
        label='Образовательная организация',
        required=False,
        error_messages={"required": "Введите наименование организации"}
    )
    education_organization_address_locality = forms.CharField(
        max_length=255,
        label="Населённый пункт",
        required=False,
        error_messages={"required": "Введите населённый пункт"}
    )
    education_organization_address_street = forms.CharField(
        max_length=255,
        label='Улица',
        required=False,
        error_messages={"required": "Введите улицу"}
    )
    education_organization_address_number_of_building = forms.CharField(
        max_length=255,
        label='Номер строения',
        required=False,
        error_messages={"required": "Введите номер строения"}
    )
    name = forms.CharField(max_length=255, label='Наименование специальности',
                           error_messages={"required": "Введите наименование специальности"})
    code = forms.CharField(max_length=9, label='Код специальности',
                           error_messages={"required": "Введите код специальности"})
    education_level = forms.ModelChoiceField(queryset=EducationLevel.objects.all(),
                                             label='Уровень образования')

    class Meta:
        model = EducationOfJobSeeker
        fields = (
            'education_organization_name', 'education_organization_address_locality',
            'education_organization_address_street', 'education_organization_address_number_of_building', 'name',
            'code', 'education_level',
            'year_received')


class WorkExperienceForm(forms.ModelForm):

    class Meta:
        model = WorkExperience
        fields = ('organization', 'position', 'date_of_employment', 'date_of_dismissal')
        exclude = ['job_seeker', ]

        widgets = {
            'date_of_dismissal': forms.DateInput(attrs={'type': 'date'}),
            'date_of_employment': forms.DateInput(attrs={'type': 'date'}),
        }


class ApplicationResponseRejectForm(forms.ModelForm):
    class Meta:
        model = ApplicationsResponses
        fields = ['description']


class JobInterviewForm(forms.ModelForm):
    tomorrow = dt.now() + timedelta(days=1)
    employee = forms.ModelChoiceField(queryset=Employee.objects.all(), label='Сотрудник')
    date_of_interview = forms.DateTimeField(widget=forms.DateTimeInput(attrs={
        'type': 'datetime-local', 'step': 60,
        'min': (dt(tomorrow.year, tomorrow.month, tomorrow.day, 9, 0)),
        'max': (dt.now() + timedelta(
            days=7)).strftime('%Y-%m-%dT%H:%M'),
    }),
        label='Время собеседования')
    locality = forms.CharField(max_length=255, label='Населенный пункт',
                               required=False)
    street = forms.CharField(max_length=255, label='Улица',
                             required=False)
    number_of_building = forms.CharField(max_length=31, label='Номер строения',
                                         required=False)
    apartment_number = forms.CharField(max_length=31, label='Номер помещения',
                                       required=False)

    class Meta:
        model = JobInterview
        fields = ['employee', 'date_of_interview', 'locality', 'street', 'number_of_building', 'apartment_number',
                  'link']

    def clean(self):
        cleaned_data = super().clean()
        locality = cleaned_data.get('locality')
        street = cleaned_data.get('street')
        number_of_building = cleaned_data.get('number_of_building')
        apartment_number = cleaned_data.get('apartment_number')
        link = cleaned_data.get('link')

        if (locality or street or number_of_building or apartment_number) and link:
            raise ValidationError(
                "Можно заполнить только одно из полей 'Место проведения' или 'Ссылка для онлайн собеседования'")
        elif not (locality or street or number_of_building) and not link:
            raise ValidationError(
                "Необходимо заполнить одно из полей 'Место проведения' или 'Ссылка для онлайн собеседования'")

        return cleaned_data


class ReviewOnInterviewForm(forms.ModelForm):
    interview_description = forms.CharField(label='Отзыв сотрудника', widget=forms.Textarea, required=True)
    CHOICES = [
        ('rejected', 'Отказать'),
        ('sent_to_employer', 'Отправить к работодателю'),
    ]
    response_status = forms.ChoiceField(label='Статус', choices=CHOICES)

    class Meta:
        model = JobInterview
        fields = ['interview_description', 'response_status']

domain/templates/job_seekers_templates/profile/create/education_create.html
{% extends 'base.html' %}
{% block content %}
    <div class="content-block flex-vertical gap-1em">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
        <link href="http://cdn.jsdelivr.net/npm/suggestions-jquery@22.6.0/dist/css/suggestions.min.css"
              rel="stylesheet"/>
        <script src="http://cdn.jsdelivr.net/npm/suggestions-jquery@22.6.0/dist/js/jquery.suggestions.min.js"></script>
        <h1 class="title">Образование</h1>
        <div class="content-box flex-vertical gap-1em">
            <div class="content flex-vertical gap-2em" style="padding: 4em 8em;">
                <form method="POST" class="input-form flex-vertical gap-2em" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="flex-vertical extra-part">
                        <div class="top-splitter-two flex-horizontal">
                            <div class="splitted-part left active" onclick="toggleSplitter(this)">Выбрать существующую
                            </div>
                            <div class="splitted-part right" onclick="toggleSplitter(this)">Создать новую</div>
                        </div>
                        <div class="flex-vertical gap-1em inner-part">
                            <div class="content flex-vertical gap-3em active-content" style="padding: 2em 4em;">
                                <p>
                                   <label for="{{ form.existing_education_organization.id_for_label }}">{{ form.existing_education_organization.label }}:</label>
                                    {{ form.existing_education_organization|add_class:"input-field" }}
                                </p>
                                Если вашей образовательной организации нет, перейдите на вкладку создания новой и
                                внесите данные о ней
                            </div>
                            <div class="content flex-vertical gap-3em inactive-content" style="padding: 2em 4em;">
                                <h1 class="title text-size-larger">Данные об образовательной организации</h1>
                                <p>
                                    <label for="{{ form.education_organization_name.id_for_label }}">{{ form.education_organization_name.label }}:</label>
                                    {{ form.education_organization_name }}
                                </p>
                                <h1 class="title text-size-larger">Адрес образовательной организации</h1>
                                <p style="display: none">
                                    <label for="{{ form.education_organization_address_locality.id_for_label }}">{{ form.education_organization_address_locality.label }}:</label>
                                    {{ form.education_organization_address_locality }}
                                </p>
                                <p class="flex-horizontal" style="display: none">
                                    <label for="{{ form.education_organization_address_street.id_for_label }}">{{ form.education_organization_address_street.label }}:</label>
                                    {{ form.education_organization_address_street|add_class:"width-180" }}
                                    <label for="{{ form.education_organization_address_number_of_building.id_for_label }}">Дом:</label>
                                    {{ form.education_organization_address_number_of_building }}
                                </p>
                                <div class="flex-horizontal gap-2em" style="align-items: baseline; "><label
                                        for="{{ form.okved_kode.id_for_label }}">Введите адрес
                                    организации:</label>
                                    <div class="flex-vertical gap-1em" style="flex: 1">
                                        <input id="address" name="address" type="text" class="input-field"
                                               style="width: 100%"
                                               value="{% if form.education_organization_address_locality.value %}{{ form.education_organization_address_locality.value }} {{ form.education_organization_address_street.value }} {{ form.education_organization_address_number_of_building.value }} {{ form.apartment_number.value }}{% endif %}"/>
                                    </div>
                                </div>
                                <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
                                <link href="http://cdn.jsdelivr.net/npm/suggestions-jquery@22.6.0/dist/css/suggestions.min.css"
                                      rel="stylesheet"/>
                                <script src="http://cdn.jsdelivr.net/npm/suggestions-jquery@22.6.0/dist/js/jquery.suggestions.min.js"></script>
                                <script>
                                    $("#address").suggestions({
                                        token: "{{ DADATA_API_KEY }}",
                                        type: "ADDRESS",
                                        /* Вызывается, когда пользователь выбирает одну из подсказок */
                                        onSelect: function (suggestion) {
                                            // Заполнение скрытых полей адреса значениями из подсказки
                                            $("#id_education_organization_address_locality").val(suggestion.data.city);
                                            $("#id_education_organization_address_street").val(suggestion.data.street);
                                            $("#id_education_organization_address_number_of_building").val(suggestion.data.house);
                                        }
                                    });
                                </script>
                            </div>
                        </div>
                    </div>
                    <h1 class="title text-size-larger">Данные об образовании</h1>
                    <p>
                        <label for="{{ form.name.id_for_label }}">{{ form.name.label }}:</label>
                        {{ form.name }}
                    </p>
                    <p>
                        <label for="{{ form.code.id_for_label }}">{{ form.code.label }}:</label>
                        {{ form.code }}
                    </p>
                    <p>
                        <label for="{{ form.education_level.id_for_label }}">{{ form.education_level.label }}:</label>
                        {{ form.education_level }}
                    </p>
                    <p>
                        <label for="{{ form.year_received.id_for_label }}">{{ form.year_received.label }}:</label>
                        {{ form.year_received }}
                    </p>
                    <button type="submit" class="button submit">Сохранить</button>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}

domain/templates/job_seekers_templates/profile/create/resume_create.html
{% extends 'base.html' %}
{% block content %}
    <form method="POST" class="input-form flex-vertical gap-2em">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="button submit">Сохранить</button>
    </form>
{% endblock content %}

domain/templates/job_seekers_templates/profile/create/skills_create.html
{% extends 'base.html' %}
{% block content %}
    <div class="content-block flex-vertical gap-1em">
        <h1 class="title">Гибкие навыки</h1>
        <div class="content-box flex-vertical gap-1em">
            <div class="content flex-vertical gap-2em" style="padding: 4em 8em;">
                <form method="POST" class="input-form flex-vertical gap-2em">
                    {% csrf_token %}
                    <p class="flex-horizontal gap-2em">
                        <label for="{{ form.skills.id_for_label }}">Гибкие навыки: </label>
                    </p>
                    <div class="flex-horizontal gap-1em" style="padding: 1em 0">
                        <label>Поиск:</label>
                        <input type="text"
                               oninput="filterCheckboxes(this, 'filter-results-container-{{ form.skills.id_for_label }}')"
                               class="input-field">
                    </div>
                    <div class="flex-vertical gap-05em checkbox-div"
                         id="filter-results-container-{{ form.skills.id_for_label }}">
                        {% for checkbox in form.skills %}
                            <div {% if checkbox.checked %}class="selected"{% endif %}>
                                {{ checkbox }}
                                {% if checkbox.name in form.initial %}
                                    <script>
                                        document.addEventListener('DOMContentLoaded', function () {
                                            document.getElementById("{{ checkbox.id_for_label }}").checked = true;
                                        });
                                    </script>
                                {% endif %}
                            </div>
                        {% endfor %}
                    </div>
                    <div style="display: none">{{ form.new_skills }}</div>
                    <div id="new-skills-container" class="flex-vertical gap gap-05em"></div>
                    <button type="button" class="button" onclick="addSkillInput()">Добавить навык</button>
                    <button type="submit" class="button submit">Сохранить</button>
                </form>
            </div>
        </div>
    </div>
    <script>
        function addSkillInput() {
            var container = document.getElementById("new-skills-container");

            var skillDiv = document.createElement("div");
            skillDiv.classList.add("flex-horizontal", "gap-2em");

            var input = document.createElement("input");
            input.type = "text";
            input.classList.add("input-field");
            input.name = "new_skills[]";
            input.placeholder = "Введите новый навык";

            var deleteButton = document.createElement("button");
            deleteButton.textContent = "Удалить";
            deleteButton.classList.add("button", "reject");
            deleteButton.type = "button";

            deleteButton.addEventListener("click", function () {
                skillDiv.remove();
            });

            skillDiv.appendChild(input);
            skillDiv.appendChild(deleteButton);

            container.appendChild(skillDiv);
        }

        var form = document.querySelector('.input-form');

        // Добавляем обработчик события для отправки формы
        form.addEventListener('submit', function (event) {
            // Получаем контейнер для новых навыков
            var container = document.getElementById("new-skills-container");

            // Получаем все созданные поля для новых навыков
            var newSkillInputs = container.querySelectorAll('input[name="new_skills[]"]');

            // Создаем массив для хранения значений новых навыков
            var newSkills = [];

            // Проходимся по каждому полю и добавляем его значение в массив
            newSkillInputs.forEach(function (input) {
                newSkills.push(input.value);
            });

            // Преобразуем массив в строку, разделяя значения запятой
            var newSkillsString = newSkills.join(',');

            // Находим поле для новых навыков и присваиваем ему собранную строку значений
            document.querySelector('input[name="new_skills"]').value = newSkillsString;
        });
    </script>
{% endblock content %}

domain/templates/job_seekers_templates/profile/create/work_experience.html
{% extends 'base.html' %}
{% block content %}
    <div class="content-block flex-vertical gap-1em">
        <h1 class="title">Опыт работы</h1>
        <div class="content-box flex-vertical gap-1em">
            <div class="content flex-vertical gap-2em" style="padding: 4em 8em;">
                <form method="POST" class="input-form flex-vertical gap-2em" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="button submit">Сохранить</button>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}